In [2]:
import numpy as np

a = np.array([[2],[3],[4],[5]])
b = np.array([[6],[7],[8],[9]])

c = a * b
d = b * a
e = np.multiply(a,b)

In [3]:
print(a)
print(b)
print(c)
print(d)
print(e)

[[2]
 [3]
 [4]
 [5]]
[[6]
 [7]
 [8]
 [9]]
[[12]
 [21]
 [32]
 [45]]
[[12]
 [21]
 [32]
 [45]]
[[12]
 [21]
 [32]
 [45]]
